worker_processes 1;
error_log __OTA_BUILDER_ROOT__/.server/nginx-error.log;
pid __OTA_BUILDER_ROOT__/.server/nginx.pid;

events {
    worker_connections 128;
}

http {
    include       __OTA_BUILDER_ROOT__/server/mime.types;
    default_type  application/octet-stream;
    access_log    __OTA_BUILDER_ROOT__/.server/nginx-access.log;

    sendfile        on;
    keepalive_timeout 65;

    server {
        listen       __OTA_PORT__;
        server_name  localhost;

        root __OTA_BUILDS_DIR__;
        autoindex on;

        location ~* \.ipa$ {
            types { }
            default_type application/octet-stream;
            add_header Content-Disposition 'attachment; filename="$request_uri"';
        }

        location ~* \.plist$ {
            types { }
            default_type application/xml;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
